Documentation: Added documentation for blocks defined for NAFNet implementation
TrystAI/restorers pull request #66
Opened 2023-03-26 17:53 UTC by Samarendra109

…ementation

Fixes #61 

Changes proposed by this PR :-

Added references to the doctrings for [SimpleGate](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L11).
 Elaborated docstrings for [ChannelAttention](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L37) with references and more details.
 Elaborated docstrings for [SimplifiedChannelAttention](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L71) with references and more details.
 Elaborated docstrings for [NAFBlock](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L100) with references and more details.
 Added references and parameters to the docstrings for [PixelShuffle](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafnet.py#L10).
 Added parameters to the docstrings for [UpScale](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafnet.py#L39).
 Added references to the docstrings for [NAFNet](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafnet.py#L85).

Request for Review: @soumik12345 @SauravMaheshkar

2023-03-26 17:54 UTC, Samarendra109 commented
@soumik12345 , @SauravMaheshkar @ariG23498 please review.

2023-03-26 17:58 UTC, soumik12345 commented
@Samarendra109 can you please change the target branch fir this PR to saurav/add-auto-docs?

2023-03-27 05:53 UTC, ariG23498 requested changes
I see there are no type hints in the docs. Do we intentionally drop them? I feel documentations should include type hints and also the shape of tensors if there is a need.

2023-03-27 05:53 UTC, ariG23498 commented on restorers/model/nafnet/nafblock.py
> +    https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136670017.pdf
I am sorry but is there a `abs` version of the paper? I don't like it when I click on a link and it starts downloading a paper.

If there is none, we can proceed with this.

2023-03-27 05:53 UTC, ariG23498 commented on restorers/model/nafnet/nafblock.py
>          factor: the amount by which the channels are scaled down
Should we not add type hints to the parameters?

2023-03-27 05:53 UTC, ariG23498 commented on restorers/model/nafnet/nafblock.py
> +    https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136670017.pdf
Same comment regarding the pdf link of paper.

2023-03-27 05:53 UTC, ariG23498 commented on restorers/model/nafnet/nafblock.py
> +        a series of Hadamard produces
This is so cool! I love it when we can render latex. Good job 😃

2023-03-27 05:53 UTC, ariG23498 commented on restorers/model/nafnet/nafblock.py
> +    https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136670017.pdf
Same comment regarding the pdf link of paper.

2023-03-27 14:34 UTC, soumik12345 requested changes
Hi @Samarendra109
I added a few commit suggestions that align with the feedback from @ariG23498 at https://github.com/TrystAI/restorers/pull/66#pullrequestreview-1358368283

**Action Items:**

1. Please remove the `Optional` type specifications, they are not required.
2. Specify the types for all the parameters in the docstring.

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
> +    https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136670017.pdf
```suggestion
    Reference:
    
    1. [Simple Baselines for Image Restoration](https://arxiv.org/abs/2204.04676)
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
>          factor: the amount by which the channels are scaled down
```suggestion
        factor (Optional[int]): the amount by which the channels are scaled down
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
> +        output of the excitation operation.
```suggestion
    1. First the input is 'squeezed' across the spatial dimension to generate a
        channel-wise descriptor.
    2. Following that the inter channel dependency is learnt by applying
        two convolution layers.
    3. Finally, the input is rescaled by a channel-wise multiplication with the
        output of the excitation operation.
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
> +    https://ieeexplore.ieee.org/document/8578843
```suggestion
    Reference:
    
    1. [Squeeze-and-Excitation Networks](https://arxiv.org/abs/1709.01507)
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
> +    https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136670017.pdf
```suggestion
    Reference:
    
    1. [Simple Baselines for Image Restoration](https://arxiv.org/abs/2204.04676)
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
> +    https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136670017.pdf
```suggestion
    Reference:
    
    1. [Simple Baselines for Image Restoration](https://arxiv.org/abs/2204.04676)
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
>          factor: factor by which the channels must be increased before being reduced by simple gate.
```suggestion
        input_channels (Optional[int]): number of channels in the input (as NAFBlock retains the input size in the output)
        factor (Optional[float]): factor by which the channels must be increased before being reduced by simple gate.
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafnet.py
> +        upscale_factor: the factor by which the input's spatial dimensions will be scaled.
```suggestion
        upscale_factor (int): the factor by which the input's spatial dimensions will be scaled.
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafnet.py
> +        pixel_shuffle_factor: the factor by which the input's spatial dimensions will be scaled.
```suggestion
        channels (int): number of channels in the input.
        pixel_shuffle_factor (int): the factor by which the input's spatial dimensions will be scaled.
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafnet.py
> +    https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136670017.pdf
```suggestion
    Reference:
    
    1. [Simple Baselines for Image Restoration](https://arxiv.org/abs/2204.04676)
```

2023-03-27 14:34 UTC, soumik12345 commented on restorers/model/nafnet/nafnet.py
>          middle_block_num: (int) denotes the number of middle blocks.
```suggestion
        filters (Optional[int]): denotes the starting filter size.
        middle_block_num: (Optional[int]) denotes the number of middle blocks.
```

2023-03-28 16:30 UTC, Samarendra109 commented
@soumik12345 , @ariG23498 I have made the changes. Please have a look

2023-04-03 03:29 UTC, soumik12345 requested changes
Hi @Samarendra109, a few more suggestions and we are good to merge.

2023-04-03 03:29 UTC, soumik12345 commented on restorers/model/nafnet/nafblock.py
> +        factor (Optional[int]): the amount by which the channels are scaled down
```suggestion
        factor (int): the amount by which the channels are scaled down
```

2023-04-03 03:29 UTC, soumik12345 commented on restorers/model/nafnet/nafnet.py
> +        filters (Optional[int]): denotes the starting filter size.
```suggestion
        filters (int): denotes the starting filter size.
```

2023-04-03 03:29 UTC, soumik12345 commented on restorers/model/nafnet/nafnet.py
> +        middle_block_num (Optional[int]): denotes the number of middle blocks.
```suggestion
        middle_block_num (int): denotes the number of middle blocks.
```

2023-04-03 04:25 UTC, Samarendra109 commented
@soumik12345 @ariG23498 please have a look. The changes were addressed.

2023-04-03 04:49 UTC, ariG23498 approved these changes
Looks good to go! 🚀

2023-04-04 12:45 UTC, merged